site_name: 'Aragon Monthly'
site_url: https://monthly.aragon.one
repo_name: 'aragon/aragon-monthly'
repo_url: 'https://github.com/aragon/aragon-monthly'
site_description: 'Aragon Monthly, a community curated monthly digital newspaper about DAOs and the Aragon ecosystem'
theme:     'material'
site_favicon: 'images/favicon.ico'
extra_css:
  - 'stylesheets/custom.css'
extra:
  palette:
    primary: 'grey'
    accent:  'cyan'
  logo:    'images/logo.svg'
  font:
    text: 'Crimson Text'
    code: 'Crimson Text'
  social:
    - type: 'github'
      link: 'https://github.com/aragon'
    - type: 'medium'
      link: 'https://blog.aragon.one/'
    - type: 'reddit'
      link: 'https://www.reddit.com/r/aragonproject/'
    - type: 'twitter'
      link: 'https://twitter.com/AragonProject'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/company/aragonproject/'
  feature:
    tabs: 'true'
pages:
  - Front Page: 'index.md'
  - News:
    - Home: 'news/index.md'
    - DAOs: 'news/daos.md'
    - Aragon: 'news/aragon.md'
    - district0x: 'news/district0x.md'
    - Ecosystem: 'news/ecosystem.md'
  - Articles:
    - Home: 'articles/index.md'
    - Editorials:
      - The district0x network in a nutshell: 'articles/editorial/the_district0x_in_a_nutshell.md'
    - Opinion pieces:
      - Thoughts On Governance and Network Effects: 'articles/opinion/thoughts_on_governance_network_effects.md'
    - Columns:
      - Start a Column!: 'articles/columns/submit.md'
  - Classifieds:
    - Home: 'classifieds/index.md'
  - Contributors:
    - Home: 'contributors/index.md'
    - Editors: 'contributors/editors.md'
    - Reviewers: 'contributors/reviewers.md'
    - Contributors: 'contributors/contributors.md'
    - Columnists: 'contributors/columnists.md'
  - Newsletter:
    - Aragon Monthly Newsletter: 'newsletter/index.md'
  - Project info:
    - Overview: 'info/index.md'
  - Guides:
    - Overview: 'guides/index.md'
