site_name: 'Aragon Monthly'
site_url: https://monthly.aragon.one
repo_name: 'aragon/aragon-monthly'
repo_url: 'https://github.com/aragon/aragon-monthly'
site_description: 'Aragon Monthly, a community curated monthly digital newspaper about DAOs and the Aragon ecosystem'
theme:
  name: 'material'
  palette:
    primary: 'grey'
    accent: 'cyan'
  font:
      text: 'Crimson Text'
      code: 'Crimson Text'
  logo:    'images/logo.svg'
  favicon: 'images/favicon.ico'
  feature:
      tabs: 'true'
extra_css:
  - 'stylesheets/monthly.css'
extra_javascript:
  - 'javascript/extra_js.js'
extra:
  social:
    - type: 'github'
      link: 'https://github.com/aragon'
    - type: 'medium'
      link: 'https://blog.aragon.one/'
    - type: 'reddit'
      link: 'https://www.reddit.com/r/aragonproject/'
    - type: 'twitter'
      link: 'https://twitter.com/AragonProject'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/company/aragonproject/'
pages:
  - Front Page: 'index.md'
  - News:
    - Home: 'news/index.md'
    - DAOs: 'news/daos.md'
    - Aragon: 'news/aragon.md'
    - Governance: 'news/governance.md'
  - Articles:
    - Home: 'articles/index.md'
    - Editorials:
      - Submit an Article!: 'guides/guide_for_submitting_articles.md'
    - Opinion pieces:
      - Submit an Article!: 'guides/guide_for_submitting_articles.md'
    - Columns:
      - Start a Column!: 'articles/columns/submit.md'
  - Classifieds:
    - Home: 'classifieds/index.md'
  - Contributors:
    - Home: 'contributors/index.md'
    - Editors: 'contributors/editors.md'
    - Reviewers: 'contributors/reviewers.md'
    - Contributors: 'contributors/contributors.md'
    - Columnists: 'contributors/columnists.md'
  - Newsletter:
    - Aragon Monthly Newsletter: 'newsletter/index.md'
  - Project info:
    - Overview: 'info/index.md'
  - Guides:
    - Overview: 'guides/index.md'
    - Guide for submitting a new Issue: 'guides/guide_for_submitting_a_new_issue.md'
    - Guide for submitting a new Pull Request: 'guides/guide_for_submitting_a_new_pull_request.md'
    - Guide for submitting News: 'guides/guide_for_submitting_news.md'
    - Guide for submitting Articles: 'guides/guide_for_submitting_articles.md'
    - Guide for submitting Classifieds: 'guides/guide_for_submitting_classifieds.md'
    - New Issue Template: 'guides/new_issue_template.md'
    - New Pull Request Template: 'guides/new_pull_request_template.md'
    - Repository structure: 'guides/repository_structure.md'
  - Archive:
    - Archive: 'archive/index.md'
    - Issue 01:
      - Front Page: 'archive/issue01/index.md'
      - News:
        - Home: 'archive/issue01/news/index.md'
        - DAOs: 'archive/issue01/news/daos.md'
        - Aragon: 'archive/issue01/news/aragon.md'
        - district0x: 'archive/issue01/news/district0x.md'
        - Ecosystem: 'archive/issue01/news/ecosystem.md'
      - Articles:
        - Home: 'archive/issue01/articles/index.md'
        - Editorials:
          - The district0x network in a nutshell: 'archive/issue01/articles/editorial/the_district0x_in_a_nutshell.md'
        - Opinion pieces:
          - TCRs - The Curation Protocol That Separates the Wheat from the Chaff: 'archive/issue01/articles/opinion/TCRs_Separating_the_Wheat_from_the_Chaf.md'
          - How can Aragon create a fairer world?: 'archive/issue01/articles/opinion/how_aragon_create_a_fairer_world.md'
          - Thoughts On Governance and Network Effects: 'archive/issue01/articles/opinion/thoughts_on_governance_network_effects.md'
        - Columns:
          - Start a Column!: 'archive/issue01/articles/columns/submit.md'
      - Classifieds:
        - Home: 'archive/issue01/classifieds/index.md'
      - Contributors:
        - Home: 'archive/issue01/contributors/index.md'
        - Editors: 'archive/issue01/contributors/editors.md'
        - Reviewers: 'archive/issue01/contributors/reviewers.md'
        - Contributors: 'archive/issue01/contributors/contributors.md'
        - Columnists: 'archive/issue01/contributors/columnists.md'
    - Issue 02:
      - Front Page: 'archive/issue02/index.md'
      - News:
        - Home: 'archive/issue02/news/index.md'
        - DAOs: 'archive/issue02/news/daos.md'
        - Aragon: 'archive/issue02/news/aragon.md'
        - district0x: 'archive/issue02/news/governance.md'
        - Ecosystem: 'archive/issue02/news/ecosystem.md'
      - Articles:
        - Home: 'archive/issue02/articles/index.md'
        - Columns:
          - Start a Column!: 'archive/issue02/articles/columns/submit.md'
      - Classifieds:
        - Home: 'archive/issue02/classifieds/index.md'
      - Contributors:
        - Home: 'archive/issue02/contributors/index.md'
        - Editors: 'archive/issue02/contributors/editors.md'
        - Reviewers: 'archive/issue02/contributors/reviewers.md'
        - Contributors: 'archive/issue02/contributors/contributors.md'
        - Columnists: 'archive/issue02/contributors/columnists.md'
    - Issue 04:
          - Front Page: 'archive/issue04/index.md'
          - News:
            - Home: 'archive/issue04/news/index.md'
            - DAOs: 'archive/issue04/news/daos.md'
            - Aragon: 'archive/issue04/news/aragon.md'
            - Governance: 'archive/issue04/news/governance.md'
          - Articles:
            - Home: 'archive/issue04/articles/index.md'
            - Columns:
              - Start a Column!: 'archive/issue04/articles/columns/submit.md'
          - Classifieds:
            - Home: 'archive/issue04/classifieds/index.md'
          - Contributors:
            - Home: 'archive/issue04/contributors/index.md'
            - Editors: 'archive/issue04/contributors/editors.md'
            - Reviewers: 'archive/issue04/contributors/reviewers.md'
            - Contributors: 'archive/issue04/contributors/contributors.md'
            - Columnists: 'archive/issue04/contributors/columnists.md'
